version: 0.2

phases:
    install:
        commands:
            - echo "Installing dependencies"
            - cd webapp
            - npm install

    build:
        commands:
            - echo "Build started on `date`"
            - cd webapp
            - npm run build

    post_build:
        commands:
            - echo "Build completed on `date`"

artifacts:
    files:
        - "**/*"
    base-directory: "webapp/dist"
    name: "frontend"
