version: 0.2

phases:
    install:
        runtime-versions:
            dotnet: 9.0.101

        commands:
            - echo "Base directory"
            - ls -al
            - echo "Installing dependencies"
            - cd backend && dotnet restore

    build:
        commands:
            - echo "Build started on `date`"
            - dotnet publish Music.Backend/Music.Backend.csproj -c Release --property:OutputPath=./bin/Release/net9.0/publish

    post_build:
        commands:
            - echo "Build completed on `date`"
            - cd Music.Backend/bin/Release/net9.0/publish && ls -al

artifacts:
    files:
        - "**/*"
    base-directory: "backend/Music.Backend/bin/Release/net9.0/publish"
    name: "backend"
