version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 20

        commands:
            - echo "Base directory"
            - ls -al
            - echo "Installing dependencies"
            - cd ./webapp
            - npm install

    build:
        commands:
            - echo "Build started on `date`"
            - cd webapp
            - npm run build

    post_build:
        commands:
            - echo "Build completed on `date`"

artifacts:
    files:
        - "**/*"
    base-directory: "webapp/dist"
    name: "frontend"
