version: "1"
services:
    frontend:
        build: ./webapp
        image: 192.168.1.136:5000/music-frontend:latest
        container_name: music-frontend
        ports:
            - "8000:80"
        networks:
            - music-network

    backend:
        build: ./backend
        image: 192.168.1.136:5000/music-backend:latest
        container_name: music-backend
        ports:
            - "8080:8080"
        volumes:
            - ./backend/assets:/backend/assets
        networks:
            - music-network

networks:
    music-network: {}
