services:
    database:
        image: postgres
        container_name: music-database
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: double-sharp-developer
            POSTGRES_DB: double-sharp
        ports:
            - 5432:5432
