services:
    database:
        image: postgres
        container_name: music-database
        environment:
            POSTGRES_USER: admin
            POSTGRES_DB: double-sharp
        env_file:
            - ./db.prod.env
        ports:
            - 5433:5432
