services:
    db-schema-update:
        build: ./backend/Music.Database
        image: localhost:5000/music-db-schema-update:20240914
        container_name: music-db-schema-update

    frontend:
        build: ./webapp
        image: localhost:5000/music-frontend:20240914
        container_name: music-frontend
        ports:
            - "8000:80"
        networks:
            - music-network

    backend:
        build: ./backend/Music.Backend
        image: localhost:5000/music-backend:20240914
        container_name: music-backend
        ports:
            - "8080:8080"
        volumes:
            - ./backend/assets:/backend/assets
        networks:
            - music-network

networks:
    music-network: {}
