services:
  frontend:
    build: ./webapp
    image: music/frontend
    container_name: music-frontend
    ports:
      - "8000:80"
    networks:
      - music-network

  backend:
    build: ./backend
    image: music/backend
    container_name: music-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/assets:/backend/assets
    networks:
      - music-network

networks:
  music-network: {}
