services:
  frontend:
    build:
      context: ./webapp
      dockerfile: ./webapp/Dockerfile
    image: music/frontend
    ports:
      - "8000:80"
    networks:
      - front-tier
      - back-tier

  backend:
    build:
      context: ./backend
      dockerfile: ./backend/Dockerfile
    image: music/backend
    ports:
      - "8080:8080"
    volumes:
      - music-files:/etc/data
    networks:
      - back-tier

volumes:
  music-files:
    external: true

networks:
  front-tier: {}
  back-tier: {}
