IF OBJECT_ID('Roles', 'U') IS NOT NULL AND OBJECT_ID('UQ_Name', 'C') IS NOT NULL
BEGIN
    
ALTER TABLE Roles
    ADD CONSTRAINT UQ_Name UNIQUE (Name)

END


IF OBJECT_ID('AccountRoles', 'U') IS NOT NULL
BEGIN
    
UPDATE AccountRoles SET AccountId = 0 WHERE AccountId IS NULL
UPDATE AccountRoles SET AccountId = 0 WHERE RoleId IS NULL

ALTER TABLE AccountRoles
    ALTER COLUMN AccountId INT NOT NULL

ALTER TABLE AccountRoles
    ALTER COLUMN RoleId INT NOT NULL

END
