services:
    database:
        image: postgres
        container_name: music-database
        volumes:
            - ./postgres-data:/var/lib/postgresql
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: double-sharp-developer
            POSTGRES_DB: double-sharp
        ports:
            - 5433:5432
    minio:
        image: minio/minio
        command: server /data --console-address ":9001"
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            MINIO_ROOT_USER: admin
            MINIO_ROOT_PASSWORD: password
        volumes:
            - "./minio-data:/data"

    minio-init:
        image: minio/mc
        depends_on:
            - minio
        entrypoint: >
            /bin/sh -c "
            sleep 3;
            mc alias set local http://minio:9000 admin password;
            mc mb local/doublesharp-files || true;
            mc anonymous set download local/doublesharp-files || true;
            mc cors set local/doublesharp-files /config/cors.xml;
            "
        volumes:
            - "./minio-conf/s3.cors.xml:/config/cors.xml"
