#:schema node_modules/wrangler/config-schema.json
name = "describe-files"
main = "src/index.js"
compatibility_date = "2024-06-20"
compatibility_flags = ["nodejs_compat"]

account_id = "5bd71e5c0bd966913bd56e0717ddc2c1"
workers_dev = true

[[r2_buckets]]
binding = 'MUSIC' # <~ valid JavaScript variable name
bucket_name = 'music'
