name: Validate Frontend
on: [push, pull_request]

jobs:
    Run-ESLint:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./webapp

        strategy:
            matrix:
                node-version: [20.x]
                architecture: [x64]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  architecture: ${{ matrix.architecture }}

            - name: Install dependencies
              run: npm install

            - name: Run ESLint
              run: npm run lint

    Build-Webapp:
        runs-on: ubuntu-latest
        needs: Run-ESLint
        defaults:
            run:
                working-directory: ./webapp

        strategy:
            matrix:
                node-version: [20.x]
                architecture: [x64]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  architecture: ${{ matrix.architecture }}

            - name: Install dependencies
              run: npm install

            - name: Build webapp
              run: npm run build
